
version: "3.8"

services:
  db:
    image: postgres:16.0
    container_name: db
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: app
    command: python main.py
    ports:
      - 8000:8000
    depends_on:
      - db

